### PR TITLE
fix: invalid profile messages and error page style

### PR DESCRIPTION
**Pull request by Leslie48197**
* fix: change invalid profile messages and solve error page style issues
* this is related to #59 
* changes can be shown in the following screenshots
404 page
user does not exist

### CODE REVIEW

**Review by nacxitl — COMMENTED** [review]
Changes look good but there are linting errors.

Also if possible we should probably remove the Avatar on the left for the error page since the user doesn't exist.

**Comment by nacxitl** [comment]
> Changes look good but there are linting errors.
> 
> Also if possible we should probably remove the Avatar on the left for the error page since the user doesn't exist.

Also the 404 page button to go back home should probably be styled like our other buttons.

For example:
image

**Comment by Leslie48197** [comment]
> > Changes look good but there are linting errors.
> > Also if possible we should probably remove the Avatar on the left for the error page since the user doesn't exist.
> 
> Also the 404 page button to go back home should probably be styled like our other buttons.
> 
> For example: image

**Comment by Leslie48197** [comment]
Thanks Rey, I changed the 404 page button style just now, it may work now.

**Comment by nacxitl** [comment]
> > Changes look good but there are linting errors.
> > Also if possible we should probably remove the Avatar on the left for the error page since the user doesn't exist.
> 
> lint issue in the ShowProfile.tsx is confusing, it looks like some console warnings, any ideas to solve this code style?

There a ton of issues that need to be addressed with eslint that have been on main for awhile but for this branch to pass the check you just need to run prettier on your changed files. `npx run prettier . --write` and then when you add the files for the commit only add the three you actually changed.

**Review by CheesyGamer77 — CHANGES_REQUESTED** [review]
I agree with Rey that the avatar on the error page should be removed. Please also run prettier to fix any formatting issues. That's why the `lint` check is currently failing for your PR.

Aside from these issues, everything works as expected and satisfies acceptance criteria, nice job

**Pull request closed without merging**
